apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
        - name: cast-service
          image: marine06l/cast_service:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              value: postgresql://cast_db_username:cast_db_password@cast_db/cast_db_dev
          volumeMounts:
            - mountPath: /app/
              name: cast-service-volume
      volumes:
        - name: cast-service-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: cast-service
  namespace: dev
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: cast-service
